# Generated by Django 4.2.5 on 2023-09-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_alter_vehicle_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='created_by',
            new_name='owner',
        ),
    ]
