# Generated by Django 4.2.5 on 2023-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0006_vehicle_description_alter_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(null=True, upload_to='vehicle_images'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seat_number',
            field=models.IntegerField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('11', '11')], default=4),
        ),
    ]
