# Generated by Django 4.2.5 on 2023-09-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0008_alter_vehicle_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='img',
            field=models.ImageField(null=True, upload_to='user-images'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
