# Generated by Django 4.2.5 on 2023-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0009_myuser_img_myuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
