# Generated by Django 4.2.5 on 2023-10-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0010_alter_myuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
