# Generated by Django 4.2.5 on 2023-10-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0013_alter_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_body',
            field=models.CharField(default='Limuuzina', max_length=15),
        ),
    ]
