# Generated by Django 4.2.5 on 2023-10-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0014_vehicle_car_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='vehicle_images')),
                ('image2', models.ImageField(null=True, upload_to='vehicle_images')),
                ('image3', models.ImageField(null=True, upload_to='vehicle_images')),
                ('image4', models.ImageField(null=True, upload_to='vehicle_images')),
                ('image5', models.ImageField(null=True, upload_to='vehicle_images')),
                ('image6', models.ImageField(null=True, upload_to='vehicle_images')),
                ('image7', models.ImageField(null=True, upload_to='vehicle_images')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='car_app.vehicle')),
            ],
        ),
    ]
